### ISSUE TITLE
Problem: rescuable is confusing

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#102]
I'm doing some big refactoring on `run.rs` so things might break hard.

**Comment by sorpaas** [comment]
Okay. As I foresee that this change might just break everything, so I'm going to create a new branch (with no commits) and then gradually move the current work there. In this way we can fall back if the process takes too long.

**Comment by sorpaas** [comment]
This shouldn't affect testing/gaslighter, and the VM's interface will be mostly preserved. However, all the internal structure will go through a massive change.

I'll also migrate the existing `vmtests` using Rust's testing framework together with this refactoring. This might take several days.

**Comment by sorpaas** [comment]
This will be carried on at https://github.com/ethereumproject/sputnikvm/tree/enhance/run-refactor using the normal C4 process.

**Comment by sjmackenzie** [comment]
Hmm please don't use topic branches on canonical, just break master, the codebase is in raw state and thus it's expected. You can keep topical branches on you fork.
