### ISSUE TITLE
Problem: Parity's RLP library has too many dependencies

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#116]
A placeholder until I finished removing them.

**Comment by ghost** [comment]
@sorpaas better to rewrite it completely, like another crate - jsonrpc. I like only bigint library, probably also tinykeccak and ethabi, simple and fast, all other libraries from paritytech overcomplicated for me.

**Comment by sjmackenzie** [comment]
I'm working on this.

**Comment by sjmackenzie** [comment]
Though, the problem seems a bit vague? What in particular is the problem? I want to strip out bigint and pull out our bigint into a separate crate. Then swap out the deprecate serialization for serde.

**Comment by sorpaas** [comment]
Okay, yeah this issue seems a bit vague. I'm closing it until I find a better way to describe the problem.
