### ISSUE TITLE
Problem: get_block_by_number throws "json: cannot unmarshal string into Go value of type bool"

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#139]
After adding a few print statements in key locations

```
method: "eth_getBlockByNumber"
params: ["0xc11f", "false"]
response: "{\"jsonrpc\":\"2.0\",\"id\":2,\"error\":{\"code\":-32602,\"message\":\"json: cannot unmarshal string into Go value of type bool\"}}\n"
```

The response contains an unmarshal error. 

I'm keen to know your setup or if your setup produces this error.

related to #122

**Comment by sorpaas** [comment]
`parity --chain=classic --pruning=archive`

**Comment by sjmackenzie** [comment]
ah that's related to your comment on #122 thanks!

**Comment by sjmackenzie** [comment]
@whilei is there an equivalent for `--pruning=archive` in geth?

**Comment by whilei** [comment]
Not as far as I know.

**Comment by sorpaas** [comment]
@sjmackenzie @whilei I think geth is `pruning=archive` by default unless you pass `--fast`.

**Comment by whilei** [comment]
I was wondering about exactly that. Think you're ~~probably~~ right.

**Comment by sjmackenzie** [comment]
I'll test shortly!
