### ISSUE TITLE
Feature: wrapping transactions for VM

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#152]
Part of #122

**Comment by sjmackenzie** [comment]
How does this help?

**Comment by sjmackenzie** [comment]
Why is "Wrapping transactions for the VM" a problem?

**Comment by sjmackenzie** [comment]
It seems you're naming each problem after the abstraction level... with this approach why not name each commit "Problem: No standalone blockchain virtual machine under Apache 2 License" it's a hierarchy of problems and naming each problem after the abstraction/interface/composition problem level has only served to make it harder to understand.

**Comment by sjmackenzie** [comment]
Just looking at this page is hard to understand. @dulanov is this what you meant by your composition problem?

**Comment by sorpaas** [comment]
"Problem: No standalone blockchain virtual machine under Apache 2 License" is a valid problem, and it can be divided into "Feature: blockchain regression test", "Feature: reduce memory footprint", etc.

If you are not familiar with SputnikVM internals, this problem might be hard to understand. "Wrapping transactions for the VM" is not a problem statement itself. The problem statement is "Blockchain regression test is hard to implement if we don't wrap transaction for the VM struct". We utilize the "Feature:" keyword and use hierarchical issues to make the whole structure clearer.

Anyway, next time if an issue is hard to understand, try to take a look of SputnikVM internals first! 😂

**Comment by sjmackenzie** [comment]
I suspect you missed my point. Newcomers to this issue just see a wall of the same problem, when quite clearly a problem can be broken up into more granular problems such as #122.

**Comment by sorpaas** [comment]
Yes, you're right. We should get our tutorials and docs better for others to understand SputnikVM internals. So if a newcomer does not understand what this issue is about, he or she can easily refer to those docs, and come back.
