### ISSUE TITLE
Feature: reduce memory footprint

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#162]
Use reference instead of heap allocated objects to reduce footprint.

**Comment by sjmackenzie** [comment]
Have we had memory footprint problems yet?

**Comment by sorpaas** [comment]
Yes. Have a look at the recursive attack problem.

**Comment by sjmackenzie** [comment]
Okay great, as the #161 is logged I'm closing this duplicate.

**Comment by sorpaas** [comment]
Oh don't close this. There're other recursive attack problems not covered by #161.

**Comment by sjmackenzie** [comment]
New issues should be opened for them, otherwise we'll have long standing issues that are placeholders for hypotheticals on top of hypotheticals. What are these other issues?

**Comment by sorpaas** [comment]
This basically plans to replace `Vec<u8>`s in `Context` and `PC` to reference of bytearrays. That is why this is logged as a feature issue -- multiple recursive attack problems can be solved by this. At the same time, a "performance is bad" problem can also be logged.

**Comment by sorpaas** [comment]
https://github.com/ethereumproject/easm/issues/3 solves the code `Vec<u8>` overhead. We can solve the data `Vec<u8>` overhead by using a linked list of `Box<Machine>`.

**Comment by sorpaas** [comment]
But I'm going to delay data `Vec<u8>` overhead for later -- memory costs gas, so there's no attack that can be planted using data `Vec<u8>`.

**Comment by sorpaas** [comment]
We've already fixed most of the major memory footprint issue, so let's close this tracking issue.
