### ISSUE TITLE
Problem: Blockchain regression CI requires a running node

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#168]
Part of #122. I can use That World's Jenkin server for CI setup.

Currently, the only problem for setting up a CI is to find a good public RPC endpoint. This seems to be a problem right now. HTTP nodes are preferred to HTTPS nodes, as we don't need additional dependencies. A suitable candidate is http://api.gastracker.io/web3, however, it does not work against the current setup.

@sjmackenzie Can you help to test `regtests` running against a local Geth RPC endpoint?

**Comment by sjmackenzie** [comment]
please do not use your personal server for this, we will arrange a proper setup.

**Comment by sorpaas** [comment]
@sjmackenzie Could you help to confirm that `regtests` works for Geth, please?

**Comment by sjmackenzie** [comment]
okay sure, busy on work atm, will check it out a bit later.

**Comment by sorpaas** [comment]
Oh, you're working on other projects than SputnikVM? Then no worry!

**Comment by sorpaas** [comment]
Confirmed, both http://api.gastracker.io/web3 (because of lack of support of some RPC functions) and https://mewapi.epool.io (because of lack Parity's archive mode) do not work. We'll need to setup a private node.
