### ISSUE TITLE
Regression: Block 1-1150000 using FRONTIER_PATCH

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#172]
Part of #122. Two servers are being used to conduct the regression test:

- `nulltl-big`: [That World's Jenkin CI](https://jenkins.that.world/job/SputnikVM%20Blockchain%20Regression%20Ongoing/).
- `sputnikvm1`: a private server.

Current status:

- Block 1..200000: `nulltl-big`. finished.
- Block 200000..300000: `sputnikvm1`, job 1. finished.
- Block 300000..400000: `sputnikvm1`, job 2. finished.
- Block 400000..500000: `sputnikvm1`, job 3. finished.
- Block 500000..600000: `sputnikvm1`, job 4. finished.
- Block 600000..700000: `sputnikvm1`, job 5. finished.
- Block 700000..800000: `sputnikvm1`, job 1. finished.
- Block 800000..900000: `sputnikvm1`, job 2. finished.
- Block 900000..1000000: `sputnikvm1`, job 3. finished.
- Block 1000000..1100000: `sputnikvm1`, job 4. finished.
- Block 1100000..1150000: `sputnikvm1`, job 5. finished.

**Comment by sjmackenzie** [comment]
Problem statement not clear. Please explain what this means.

**Comment by sorpaas** [comment]
You'll need to have certain knowledge of SputnikVM to understand this. Have a read of what `FRONTIER_PATCH` is in SputnikVM. If you still cannot understand what this is after that, let me know.

**Comment by sorpaas** [comment]
We've just finished this regression test.
