### ISSUE TITLE
Problem: patch wars in Github issues affect development

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#175]
Currently there're ongoing patch wars #172, #173, #174, #122. Those affect SputnikVM's development process.

While we aim to resolve them, before they are settled, all important issues are being moved to the [wiki page](https://github.com/ethereumproject/sputnikvm/wiki/Roadmap). This issue documents the process.

**Comment by sorpaas** [comment]
Blockchain regression process can be found at https://github.com/ethereumproject/sputnikvm/wiki/Blockchain-Regression

**Comment by sorpaas** [comment]
Memory footprint reduction process can be found at https://github.com/ethereumproject/sputnikvm/wiki/Reduce-Memory-Footprint

**Comment by sorpaas** [comment]
RPC process can be found at https://github.com/ethereumproject/sputnikvm/wiki/SputnikVM-RPC

**Comment by sjmackenzie** [comment]
Please do not use the wiki to track issues.

**Comment by sorpaas** [comment]
No Stewart, until this patch war is stopped, using wiki to track issues is a reasonable choice. Right now Github issues is just unusable.

**Comment by sorpaas** [comment]
Anyway, I'm going to close this, to prevent patch wars on this issue.....

**Comment by sorpaas** [comment]
We seemed to find a way to stop those patch wars. I'm going to reopen this issue to document the process.

**Comment by sjmackenzie** [comment]
close due to irrelevance.

**Comment by sorpaas** [comment]
Reopening this. This is so relevant to us. The patch wars started by @sjmackenzie have affected SputnikVM's development so much, and we should seriously consider abandoning C4 which is believed to be the main cause of the current problem we are facing.

**Comment by sorpaas** [comment]
Reopening this. I have no idea what's happening right now.

**Comment by sorpaas** [comment]
There seems to be something wrong with the current `master` branch. Until that issue is resolved, I'm going to skip using `master` branch by all means and use `develop` branch for all development and releases.

**Comment by sorpaas** [comment]
Solved by moving the repo to https://github.com/ethereumproject/esvm
