### ISSUE TITLE
Problem: implementing needed features in u256 requires constant bumping on crates.io

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#2]
Solution: move the github.com/sorpaas/u256 file into sputnikvm to reduce development latency. Once u256 stabilizes we can move it out to sorpaas/u256 and bump the crate.

**Comment by sorpaas** [comment]
Agreed! So let's make it a git submodule probably?

**Comment by sorpaas** [comment]
@sjmackenzie Or would it be better to use a git head checkout in `Cargo.toml`? In this way we can avoid polluting spunikvm's namespace.

**Comment by sjmackenzie** [comment]
Oh dear, we'll have a conflict with my PR. @sorpaas please rebase and push to your PR without the Issue 1 commit. It's probably better to keep the u256 in the repo entirely. 

Why? I personally really dislike it when there are git statements in cargo. Cargo does too much anyway, it'll also break my `nixcrates` when the time comes.

Solved in: https://github.com/ethereumproject/sputnikvm/pull/3/commits/ea2b067f40e1e8154c4c23baf4af2eb3a3af6afe

**Comment by sjmackenzie** [comment]
actually don't worry about merging, the objective of this process is to remove upfront consensus as much as possible. I'll merge your work then amend it.
