### ISSUE TITLE
Patch interface tracking issue

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#266]
Ping @whilei @sudachen who might be interested in this issue.

The patch interface, basically, is to use generic types (in Rust, it's trait, and in Go, I think interface is a similar concept) for representing different rules across hard forks. Here I will use the ECIP1017 as an example to explain the design difference between sputnikvm/etcommon and geth/parity.

The geth one implements ECIP1017 as a parameter, so we have something like this:

```
In post-processing of a block {
  // Apply block rewards
  Do something;
  If (ECIP1017 is enabled) {
    Do something else;
  }
}
```

This has the advantage that those parameters can be easily represented as a json file. However, it adds code complexity and consider if another ECIP9999 is built on top of ECIP1017, we would have another nested if statement, so forth and so on. It also makes it so that if geth is used as a library, it is not possible to extend it with ECIP9999 without changing code in the library.

The sputnikvm/etcommon way is to get this into a generic type:

```
In post-processing of a block < based on a generic type > {
  // Apply block rewards
  Do something;
  Do something else based on the generic type (which the implementation is in the generic type);
}
```

So with ETC we call `In post-processing of a block < ECIP1017 >` and for ETH we call `In post-processing of a block < Frontier >`.

This has the advantage that it is easily extensible if used as a library. I can add any new block reward rules by implementing this generic type. However, it suffers the problem that those Patch will not be able to easily represented as a JSON file -- the main rules must be specified in Rust code.

The implementation detail is that there will be several patches, one for VM, one for transaction signing, one for block rewards, etc. Those patches will then be joined together by an overall patch using Rust's associate types. They will then be used in a block `Processor` whose rules is based on the patches. A `Client` struct, after given a block number, will return (using Rust's trait dynamic dispatch) the corresponding `Processor` under the current hard fork. You can see this makes it a little bit easier to implement dynamic hard fork numbers.

**Comment by whilei** [comment]
Thanks for the explanation! I do like the interface pattern in the code, and think it definitely warrants at least some experimental refactoring in geth to adopt it too.

Shifting complexity from code to configuration, _ie_ from (simpler JSON/configuration + more complex code) -> (more complex JSON/configuration + simpler code), seems to me to be a significant issue. How to make a generic interface/trait configurable _and_ extensible, particularly given that future required fork functionalities will be varied and are unpredictable (like block reward calculation vs. required hashes vs. gastables, etc.)? Hmm.

I will keep thinking about it.

**Comment by whilei** [comment]
I realizeI should first ask What do you imagine (or already know?) the JSON config (if indeed it is JSON) would look like for the "generic-able" pattern?

**Comment by whilei** [comment]
Oops

**Comment by sorpaas** [comment]
@whilei I don't imagine it will be JSON config. JSON config might always have trouble to be generic enough. For one thing, Parity was never able to support Ubiq due to its slightly modified difficulty algorithm. We might also have chains that want to change the reduction rate of ECIP1017, which the current config will also not support. We also see that Parity usually have some minor problems on a non-foundation chain, like its UI price indicator, among other things. So as I see it, (which might actually be a good feature) JSON config cannot support chains that the developer does not foresee.

Instead the sputnikvm/etcommon way might look like this -- You have small basic building components like the VM, `Block`, `Transaction`, etc. Each of the components supports a number of `Patch` that allows it to be of customization. The joining components (like `Client`, `Processor`, etc) also have similar joined `Patch` structures. So for chains that is closely similar to Ethereum, it will only need to create a new patch. The difference here is that now "patches" have the ability to run code. This makes it so that it can support chains like Ubiq without knowing it in the first place. If a chain is not similar to Ethereum, it can selectively use any of the structs/traits it wants and then rewrite `Client` for its own chain.

So in this way, chains, instead of needing to fork parity/geth to modify JSON spec for an "official" support of its own, will mark sputnikvm/etcommon/etclient as a dependency, and build a small wrapper executable on top of it. From there it can build its own UI and other components without worrying about any other chains.

**Comment by sorpaas** [comment]
The new patch interface finally propagates to the client level. If you're interested in helping out the design or want to know how it works, have a look at https://github.com/sorpaas/etclient/blob/master/src/patch.rs and https://github.com/sorpaas/etclient/blob/master/src/validator/mod.rs#L114
