### ISSUE TITLE
Problem: Hand-written tests are not complete

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#30]
For testing edge cases of this EVM, hand-crafting a large amount of tests is overwhelming as we have limited man-power. One thing we can do is code review -- to make sure all codes comply with the yellow paper. Here I propose an additional method to address this problem -- by re-runing all the transactions in the existing ETC blockchain and make sure they return the same result using several different ETC clients and our SVM. I call it "compliance test".

## Method 1: Full Node

We can use one or multiple existing ETC clients to run a full node. Those full nodes have all its internal states of all the accounts maintained. So we can extract them, and then re-run the transaction using SVM.

## Method 2: Using A Blockchain Explorer

This makes it so that we don't need to download more than 30GB of data if we only want to test against several recent blocks. Many ETC explorer (such as `gastracker.io`) has the input details of a transaction and additional transactions it triggers if it is a message call (see https://gastracker.io/tx/0x1a2ce1a9128eaf575244278c89a822198ae4002454e9dd434f5291677d4a8d9e for an example). However, storage information and output details are not in the explorer, which might be a problem.

**Comment by sjmackenzie** [comment]
I hear you, i'd prefer a solution that runs upon every CI run. how about code write ethereumproject/tests into our tests?

**Comment by sorpaas** [comment]
Yeah I'm working on that right now. But for long-term, a long-running CI that would do this "compliance test" would be terrific!

**Comment by sjmackenzie** [comment]
Agreed!

Though some test code inputs are quite long.

Also we will need to carefully evolve this code writer as we add things
like externalities and more parameters.
