### ISSUE TITLE
Morden chain split at block 2057157

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#304]
The relevant transaction hash is `0xc59d9f9bb423a30e7d9764f4fa0185e5557193648b4c24f2a03e1079c8641e52`.

* From `0x2843c155c51494a684906e386120e8c2582dff5d`
* Invokes `0x0244f973e08e03b734f10136046311ce2ebddfd7`

This has no input information and the account has no data.

**Comment by whilei** [comment]
whoa 👓 wow weird what

**Comment by sorpaas** [comment]
Closed. This has nothing related to SputnikVM. It was due to bad chain config of starting nonce. Will patch geth.
