### ISSUE TITLE
Customization of Pre-compiled Contract

### ISSUE THREAD

**Issue by harishbm34** [ETCDEVTeam/sputnikvm#351]
Hi Team,  How can we customize the sputnikvm precompiled contracts to use it in solidity?

**Comment by b00f** [comment]
It would be very useful if pre-compiled contracts can be defined like a plugin library. 
Is there any way to define pre-compiled address without forking the code-base?

**Comment by mersinvald** [comment]
@b00f @harishbm34 sure, you can define your own `Patch` and define precompiled contracts in it.
Precompiled contracts for `Byzantium` hardfork are already implemented as separate crates.

For examples, please refer to https://github.com/ETCDEVTeam/sputnikvm/blob/f7a7cf8f76788ff161fdac25faae754432562261/network/classic/src/lib.rs

**Comment by mersinvald** [comment]
@harishbm34 @b00f any follow-up questions about the subject, or I can close the issue?
