### ISSUE TITLE
Predicting the address of a contract

### ISSUE THREAD

**Issue by mlr-msft** [ETCDEVTeam/sputnikvm#362]
I'm working on embedded SputnikVM within an application. 

Currently, I need to be able to predict the address of the account a solidity contract will be deployed to, given the sender's address (`:Address`) and a nonce (`:U256`).

I've gotten the address computation working as described [here](https://ethereum.stackexchange.com/questions/760/how-is-the-address-of-an-ethereum-contract-computed). Unfortunately, while the addresses my code generates match the canonical examples provided, my code does not accurately predict the account addresses SputnikVM deploys my contract to.

I can't find where in the VM implementation this calculation is performed. Am I missing something?

Thanks in advance.

**Comment by splix** [comment]
It should be same. Can you provide an address+nonce you used?

**Comment by mersinvald** [comment]
Look for address calculation here: https://github.com/ETCDEVTeam/etcommon-rs/blob/master/block-core/src/transaction.rs

**Comment by mlr-msft** [comment]
Thanks! That's really helpful. I hadn't thought to search your other repositories for the information I needed.

I'll just call your implementation to predict the address.
