### ISSUE TITLE
sputnikvm-network-* are outdated

### ISSUE THREAD

**Issue by b00f** [ETCDEVTeam/sputnikvm#366]
All sputnikvm-network-* crates  (like https://crates.io/crates/sputnikvm-network-classic) are not working with latest version of sputnikvm. 
Reason: Thw `has_bitwise_shift` and `has_extcodehash` are missed in these crates.

**Comment by mersinvald** [comment]
Outdated compared to the `master` -- true. And these are not the only methods missing. Crates are up to date with the latest SputnikVM crates.io release.

Check out the docs.rs pages.
https://docs.rs/sputnikvm/0.10.1/sputnikvm/trait.Patch.html
https://docs.rs/sputnikvm-network-classic/0.10.1/sputnikvm_network_classic/struct.EIP150Patch.html
