### ISSUE TITLE
What is the purpose of last else block in the screen below. 

### ISSUE THREAD

**Issue by harishbm34** [ETCDEVTeam/sputnikvm#372]
![screenshot 2018-11-27 at 11 06 55 am](https://user-images.githubusercontent.com/33799037/49056322-48e62c00-f236-11e8-8fda-e03c50a5202d.png)

Check the code [here](https://github.com/ethereumproject/go-ethereum/blob/master/core/multivm_processor.go)

**Comment by mersinvald** [comment]
Please direct the question to the [etheriumproject/go-etherium](https://github.com/ethereumproject/go-ethereum) repo
