### ISSUE TITLE
Problem: FromStr trait is not used

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#40]
There's the FromStr (https://doc.rust-lang.org/std/str/trait.FromStr.html) trait in the standard library. It's better to make all the current `from_str` methods comply with it.

**Comment by ghost** [comment]
I try always in `emerald-rs` try to reuse `Default`, `FromStr`, `From`, `AsRef` as well.

**Comment by ghost** [comment]
FYI: https://llogiq.github.io/2015/07/30/traits.html

**Comment by sorpaas** [comment]
Still being implemented: `H256`, `Address` and `Gas`.
