### ISSUE TITLE
Problem: test `ackermann33` fails

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#63]
We'll need to have a closer look into this test in file `vmPerformanceTest.json`.

The test does not contain "out", so gaslighter expects it to fail. However, spunikvm runs it succeeded without any problem. The full code for this test is:

```
0x60e060020a6000350480632839e92814601e57806361047ff414603457005b602a6004356024356047565b8060005260206000f35b603d6004356099565b8060005260206000f35b600082600014605457605e565b8160010190506093565b81600014606957607b565b60756001840360016047565b90506093565b609060018403608c85600186036047565b6047565b90505b92915050565b6000816000148060a95750816001145b60b05760b7565b81905060cf565b60c1600283036099565b60cb600184036099565b0190505b91905056
```

**Comment by sorpaas** [comment]
This program might be better debugged by using EDB's `fire debug`. The current return value is:

```
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 61]
```

We'll need to figure out what this program actually do and then check whether this return value is correct or not. Or whether it should actually return an error.

**Comment by sorpaas** [comment]
The tests `arith` and `boolean` in `vmtests.json` are of the same problem -- they don't contain "out", while runs successfully.

**Comment by sjmackenzie** [comment]
`out` is for chaining vm executions together sub-vm calls, so to say. If the objective is to just test whether the expected output of storage is equal to the actual output of storage then that should be enough information to qualify. Surely there's no need for `return_values` (aka out) in the situation of `arith` and `boolean` tests?

**Comment by sorpaas** [comment]
But most of the tests, even if the return value is 0x0, would contain it (`"out": "0x"`). Tests meant to fail indeed do not contain them.

These three are the exceptions I found that a) execute on the VM successfully, and b) no "out" column.

**Comment by sorpaas** [comment]
This problem seems to be fixed after integrating gas cost check.
