### ISSUE TITLE
Problem: Travis build always fail due to rocksdb dependency

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#83]
Is this under active usage (I remember we're switching to leveldb for the blockchain regression)?

Also, at this stage, the library doesn't have any plan for any non-cargo dependency. There might be one or more dependency (`merkle`, for example). However, after #79 is applied, sputnikvm dependency will be specified using `path = "../sputnikvm"`. This again breaks the Nix building system. Right now it seems that Nix still doesn't bring us many benefits. So do you think it is okay to temporarily switch to the standard rust environment for Travis before `nixcrates` is finished?

**Comment by sjmackenzie** [comment]
Sure you can but please get the travis std env to clone the tests repo and run the tests against gaslighter. Recksdb can be killed

**Comment by sjmackenzie** [comment]
fixed in https://github.com/ethereumproject/sputnikvm/pull/85
