### ISSUE TITLE
Problem: interpreter is not yet supported

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#94]
One can imagine a language built on top of SputnikVM. It works as an interpreter (like `python` and `irb`). Every time when the user enters a command, it compiles that command into EVM byte codes and send it to SputnikVM.

This functionality can be easily added by making PC replaceable -- every time, a new PC is used for the execution, with Memory and Stack kept the same. However, this currently add some accidental complexity. So I'm only planning to do this after the tests have mature.

**Comment by sjmackenzie** [comment]
Yes, a narrow compilation scope is good for executing small code snippets. The accidental complexity probably involves locks to Stack and Memory access. :-)

**Comment by sjmackenzie** [comment]
But I'd suggest we keep the problems real world and not hypotheticals, so I'm closing this issue till it actually becomes a problem!
