### ISSUE TITLE
Problem: socket protocol interface design

### ISSUE THREAD

**Issue by sorpaas** [ETCDEVTeam/sputnikvm#95]
We've got a basic communication mechanism for SputnikVM. It works like this:

1. Client creates a new VM either through an execution context, a message call transaction, or a contract creation transaction.
2. Client fires or steps the VM, and inspects the internal of the VM. The VM will return either `OK`, an `Err`, or a `NeedMoreInfo`.
3. If the VM returns an error, the internal of the VM will not be changed.
4. `NeedMoreInfo` can be `RequireAccount`, `RequireAccountCode`, `RequireBlockhash`. The client then knows it needs to commit the relevant information back to the VM and fire it again.
5. The VM never mutates state outside of itself.
6. The VM handles CALL/CREATE transaction execution without any need from the client.
7. When the execution is finished or in the middle, the client can inspect the state to be changed if the client wants to accept the result of the VM. This includes account information (either full account information, or an increase/decrease of balance), logs and transactions.

Now we need to design a `capnp` or `json` schema and communication method for the socket protocol.

**Comment by sjmackenzie** [comment]
perfect, but before we do this. I feel very uncomfortable using an "error" to direct code execution flow, let's first isolate / come up with a name that'll describe this valid approach. It's basically an optimistic execution but will fail if there's an extern call. So in this way it's functionally deterministic. In another way it could be seen as a type of machine learning. In that one could have some kind of inline cache which remembers the needed state for X contract. (I'm not proposing that this is implemented).

**Comment by sjmackenzie** [comment]
`Need More Information` -> `NMI`. I'd prefer we use this convention over an error. We delegate the concept of an error to be an actual execution problem of the VM. Does this sound reasonable?

**Comment by sjmackenzie** [comment]
Please continue discussion about `NMI` here: https://github.com/ethereumproject/sputnikvm/issues/96

**Comment by sorpaas** [comment]
I updated the description accordingly. We can use this now to design the protocol first.

**Comment by sorpaas** [comment]
Being done as https://etcrfc.that.world/16-EVMJSON

**Comment by sjmackenzie** [comment]
Correct reference is https://github.com/ethereumproject/rfc/tree/master/16 as etcrfc.that.world will be deprecated
