### ISSUE TITLE
Problem: the concept of an error is used to describe a VM's Need More Information

### ISSUE THREAD

**Issue by sjmackenzie** [ETCDEVTeam/sputnikvm#96]
## Potential Solution: 

Rename the "need more information" "error" to be a `Need More Information` or `NMI` concept. 
This keeps the semantics clear, it also means that when we speak about an error in execution it very clearly means the VM failed to execute.

**Comment by sorpaas** [comment]
Totally agreed. We should have another `Result` type. `ExecutionResult<R, N, E>`, where `R` is the return type, `N` is NMI, and `E` is Error.

**Comment by sorpaas** [comment]
But I'm going to postpone this until the next refactoring is done. That's a little bit more urgent.

**Comment by sorpaas** [comment]
@sjmackenzie However, as I think deeper about this. The problem for using three type parameters is that `trr!` and Rust's `try!` and question mark syntax is dependent on the Result type. Most of the time, the control flow handling logic for `NMI` and `Error` are the same. So I think this is better handled by creating a `NMI` enum in `ExecutionError`. But as this doesn't affect any of the structure or logic of the sputnikvm design. This will probably be postponed a little bit till the next refactoring.

**Comment by sjmackenzie** [comment]
Yes the control flow handling is exactly the same, but the semantics are different and now unambiguous - although `NMI` is a bit obtuse, maybe `NeedMoreInfo` is better!

**Comment by sorpaas** [comment]
Closed via #105
